grocsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myApp1.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myApp1/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'myApp1'
urlpatterns = [
                  path('', views.index, name='index'),
                  path('login/', views.loginPage, name='loginPage'),
                  path('logout/', views.logoutUser, name='logoutUser'),
                  path('signup/', views.signup, name='signup'),
                  path('about/', views.about, name='about'),
                  path('showMovie/', views.showMovie, name='showMovie'),
                  path('movieDetail/<str:movie_id>', views.movieDetail, name='movieDetail'),
                  path('orderMovie/<str:movie_id>', views.orderMovie, name='orderMovie'),
                  path('movieList/', views.movieList, name='movieList'),
                  path('fetchOrderedMovies/', views.fetchOrderedMovies, name='fetchOrderedMovies'),
                  path('movies/', views.movies, name='movies'),
                  path('movies/<str:movie_id>', views.movie_detail, name='movie_detail'),
                  path('movies/<str:movie_id>/similar', views.similar_movies, name='similar_movies'),
                  path('profile/', views.accountSettings, name='account_settings'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/partials/navbar.html
{% load static %}

<style>
  .navbar{
      display: flex;
    position: fixed;
    top: 0;
    z-index: 9999;
    width: 100%;

  }
  .avatar{
      width: 50px;
  }
  .actions{
      display: flex;
    margin-right: 10px;
  }
  .actions > .parent{
      display: flex;
    flex-direction: column;
    justify-content: space-between;
  }
    .logout-button{
      width: 100%;
  }
    .logo{
        height: 100px;
        width: 100px;
    }
    .avatar-container{
        margin-left: 10px;
    align-items: center;
    display: flex;
    flex-direction: column;
    }
</style>
<div class="navbar" id="navbar">
    <div class="logo">
                <a href='/'>

            <img  src="{% static 'M_Movies.jpeg' %}" alt="logo" class="logo rounded-lg">
        </a>
    </div>
    {% if AUTH != 'false' %}
    <div class="actions">
        <div class="parent">
            <div>
                <form action="{% url 'myApp1:logoutUser' %}" method="post">
                        {% csrf_token %}

                        <button class=' logout-button bg-primary_red text-white md:text-lg rounded-md'>
                            Logout
                        </button>
                </form>
            </div>
            <div>
                                    <a href="{% url 'myApp1:fetchOrderedMovies' %}" class="">
                        <button class="flex items-center bg-white rounded-md"
                                style='color:black;'>
                            <ion-icon name="list-outline" class="text-2xl p-1"></ion-icon>
                            <span class="text-sm p-1">
                                Ordered
                            </span>
                        </button>
                    </a>
            </div>
        </div>

        <a href="{% url 'myApp1:account_settings' %}" style="align-items: center;display: flex;flex-direction: column;">
            <div style="margin-left: 10px;" class="avatar-container">
                <img src="{% static 'profile1.png' %}" class="avatar bg-white rounded-lg " alt="" height="100">
                <p style="text-shadow: 2px 2px 1px #FF0000;text-align: center   ">
                    {{ request.user.username }}
                </p>
            </div>
        </a>

    </div>
    {% endif %}
</div>