grocsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myApp1.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myApp1/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'myApp1'
urlpatterns = [
                  path('', views.index, name='index'),
                  path('login/', views.loginPage, name='loginPage'),
                  path('logout/', views.logoutUser, name='logoutUser'),
                  path('signup/', views.signup, name='signup'),
                  path('about/', views.about, name='about'),
                  path('showMovie/', views.showMovie, name='showMovie'),
                  path('movieDetail/<str:movie_id>', views.movieDetail, name='movieDetail'),
                  path('orderMovie/<str:movie_id>', views.orderMovie, name='orderMovie'),
                  path('movieList/', views.movieList, name='movieList'),
                  path('fetchOrderedMovies/', views.fetchOrderedMovies, name='fetchOrderedMovies'),
                  path('movies/', views.movies, name='movies'),
                  path('movies/<str:movie_id>', views.movie_detail, name='movie_detail'),
                  path('movies/<str:movie_id>/similar', views.similar_movies, name='similar_movies'),
                  path('profile/', views.accountSettings, name='account_settings'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myApp1/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True)
    profile_pic = models.ImageField(default="profile1.png", null=True, blank=True)
    settings = models.JSONField(default=dict, null=True)

    def __str__(self):
        return self.name

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        
        {% endblock title %}
    </title>
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'moviestyle.css' %} ">
    {% block others %}
    
    {% endblock others %}
</head>
<body class='bg-black text-gray-100 font-primary'>

    {% block content %}

    {% endblock content %}

    <script>
        const nav = document.querySelector('#navbar')

        document.addEventListener("scroll",e=>{

            if(scrollY>100){
                nav.classList.add('bg-gray-900')

            }else{
                nav.classList.remove('bg-gray-900')

            }
        })

    </script>
    
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    MovieHub-home
{% endblock title %}


{% block others %}
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
{% endblock others %}


{% block content %}

    {% include "partials/navbar.html" %}
    <header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"
            style="background-image: url('{% static 'background_main.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Unlimited movies, ratings and more. <br/>
                <a href='/movieList/' )>
                    <button class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                        View all movies
                    </button>
                </a>
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Watch anywhere.
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Ready to watch? Dive into movie streaming.
            </h4>


        </div>
    </header>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Enjoy on your movies.
            </h2>
            <h5 class="md:text-xl text-lg">
                Watch on Smart TVs, Playstation, Mobile, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'tv.png' %}" class="w-8/12" alt="">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center '>
            <img src="{% static 'mobile-0819.jpg' %}" class="w-8/12" alt="">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Latest shows in one place.
            </h2>
            <h5 class="md:text-xl text-lg">
                Always have something to watch.
            </h5>
        </div>

    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Something for everyone to enjoy.
            </h2>
            <h5 class="md:text-xl text-lg">
                Send kids on adventures with their favorite characters in a space made just for them.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'netflix_kid.png' %}" class="w-8/12" alt="">
        </div>
    </section>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2022</li>
            <li> Made with Django</li>
            <li>By Group 4</li>
        </ul>
    </footer>


{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}

    Login
{% endblock title %}

{% block others %}

    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
{% endblock others %}
{% block content %}


    {% include 'partials/navbar.html' with AUTH='false' %}
    <header class="min-h-screen w-full bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center py-20 bg-no-repeat"
            style="background-image: url('{% static 'background_main.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 w-6/12  flex items-center flex-col">
            <form method='POST' class="bg-black bg-opacity-70 py-8 px-4 w-8/12 rounded-md" action="">
                <h1 class="text-4xl font-semibold text-center ">
                    Log In
                </h1>
                {% csrf_token %}
                <div class="items-center text-center my-4 text-primary_red">
                    {% for m in messages %}
                        {{ m }}
                    {% endfor %}
                </div>

                {% if form.errors %}

                    <div class=" text-center my-4 text-primary_red">


                        <p class="text-primary_red ">
                            {{ form.non_field_errors }}
                        </p>


                    </div>
                {% endif %}
                <div>
                    <Label class='text-lg font-medium mb-3'>
                        Username
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="text"
                           name="username" id="id_login" placeholder="Your Username">
                </div>
                <div class='my-3'>
                    <Label class='text-lg font-medium mb-3'>
                        Password
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="password"
                           name="password" id="id_password" placeholder="Password">
                </div>
                {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                {% endif %}
                <div class="flex justify-center items-center">
                    <button class="py-2 px-4 bg-primary_red text-gray-100 font-medium text-lg rounded-md" type="submit">
                        Log In
                    </button>
                </div>

                <div class="text-center my-4">
                    <p>
                        Do not have account <a href="{% url 'myApp1:signup' %}" class="text-blue-600"> Sign Up</a>
                    </p>
                </div>
            </form>
        </div>
    </header>
{% endblock content %}

templates/movieDetail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Movie details
{% endblock title %}

{% block others %}
{% endblock others %}

{% block content %}

    {% include 'partials/navbar.html' %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover"
                 style="background-image: url('https://image.tmdb.org/t/p/w500{{ movie.poster_path }}');">
            <div>
                <h2 class="text_outlined text-6xl font-medium text-white my-4">
                    {{ movie.title }}
                </h2>
                <h2 class="text_outlined_small px-1 w-11/12 md:w-5/12">
                    {{ movie.tagline | slice:100 }}
                </h2>
                <div class="flex my-4">
                    <!--https://www.themoviedb.org/movie/496243/watch-->
                    {% if movie_added %}
                        <div class="p-2">
                            <div disabled class="flex items-center bg-gray-400 py-2 px-5 rounded-md"
                                 style='color:black;'>
                                <ion-icon name="checkmark-circle-outline" class="text-2xl"></ion-icon>
                                <span class="ml-3 font-medium">
                                Ordered
                                </span>
                            </div>
                        </div>
                    {% else %}
                        <a href="{% url 'myApp1:orderMovie' movie_id=movie.id %}"
                           class="p-2">
                            <button class="flex items-center bg-white py-2 px-5 rounded-md"
                                    style='color:black;'>
                                <ion-icon name="add-circle-outline" class="text-2xl"></ion-icon>
                                <span class="ml-3 font-medium">
                                Order
                            </span>
                            </button>
                        </a>
                    {% endif %}
                    <a href='https://www.themoviedb.org/movie/{{ movie.id }}/watch'
                       class="p-2">

                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="eye-outline" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium">
                                Watch
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <h2 class="text-gray-200 text-3xl font-medium mm-center-des">
                                Description
                            </h2>
                        </div>
                        <div class="col">
                            <div class="height-100 container d-flex justify-content-center align-items-center mm-height-10">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="review-count mm-review-count p-5">
                                        {{ movie.vote_count }} reviews
                                    </div>
                                    <div class="col">
                                        <div class="review-count mm-review-count">
                                            {{ movie.vote_average }} rating
                                        </div>
                                        <div class="ratings mm-ratings flex-col">
                                            {% for star in "*"|rjust:"5" %}
                                                {% if forloop.counter > voting_5_star_scale %}
                                                    <i class="fa fa-star"></i>
                                                {% else %}
                                                    <i class="fa fa-star rating-color mm-rating-color"></i>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="flex justify-center p-8 items-center min-w-full">
                    <p class="text-gray-100 text-lg">
                        {{ movie.overview }}
                    </p>
                </div>
                <p>Released: {{ movie.release_date }}</p>
                <p>Duration: {{ movie.runtime }} minutes</p>
            </div>
        </section>

    </main>

{% endblock content %}

templates/movieList.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Movies
{% endblock title %}

{% block others %}

{% endblock others %}
{% block content %}


    {% include 'partials/navbar.html' %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover"
                 style="background-image: url('https://image.tmdb.org/t/p/w500{{ movie.poster_path }}');">
            <div>
                <h2 class="text_outlined text-6xl font-semibold text-white my-4">
                    {{ movie.title }}
                </h2>
                <p class="text_outlined_small w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{ movie.overview }}
                </p>
                <div class="flex my-4">
                    <!--https://www.themoviedb.org/movie/496243/watch-->
                    <a href='https://www.themoviedb.org/movie/{{ movie.id }}/watch'>

                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium">
                                Play
                            </span>
                        </button>
                    </a>


                </div>
            </div>
        </section>

        <!--new UI cards-->
        <div class="cards">
            {% for movie in top_rated_movies %}
                <a href="{% url 'myApp1:movieDetail' movie_id=movie.id %}" class="card">
                    <img src="{{ image_prefix }}{{ movie.poster_path }}"
                         class="w-full h-full border-round"
                         alt="{{ movie.title }}">
                    <div class="card__overlay">
                        <div class="card__header">
                            <img class="card__thumb" src="{{ image_prefix }}{{ movie.poster_path }}"
                                 alt="card poster path"/>
                            <div class="card__header-text">
                                <h3 class="card__title card__text_outlined">
                                    {{ movie.title }}
                                </h3>
                                <span class="card__status card__text_outlined">
                                    {{ movie.vote_average }}
                                </span>
                            </div>
                        </div>
                        <p class="card__description">{{ movie.overview | slice:200 }}...</p>
                    </div>
                </a>
            {% endfor %}
        </div>
        <!--popular_movies-->
        <div class="text-gray-200 text-2xl p-8">Popular</div>
        <section class='bg-primary_black px-5 flex-shrink-0 justify-center' style="overflow-x: scroll">
            <div class="px-5 w-10/12 relative">
                <div class="flex items-center min-w-full">
                    {% for movie in popular_movies %}

                        <a href="{% url 'myApp1:movieDetail' movie_id=movie.id %}">

                            <div class=" h-40 m-4  bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer w-40">
                                <img src="{{ image_prefix }}{{ movie.poster_path }}" class="w-full h-full "
                                     alt="{{ movie.title }}">
                            </div>
                            <div class="m-4  overflow-hidden flex-shrink-0 rounded-md cursor-pointer w-40">
                                <h5>{{ movie.title }} </h5>
                            </div>


                        </a>
                    {% endfor %}


                </div>
            </div>
        </section>
        <!--upcoming_movies-->
        <div class="text-gray-200 text-2xl p-8">Upcoming</div>
        <section class='bg-primary_black px-5 flex-shrink-0 justify-center' style="overflow-x: scroll">
            <div class="px-5 w-10/12 relative">
                <div class="flex   items-center min-w-full  movie_lis">
                    {% for movie in upcoming_movies %}

                        <a href="{% url 'myApp1:movieDetail' movie_id=movie.id %}">

                            <div class=" h-40 m-4  bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer w-40">
                                <img src="{{ image_prefix }}{{ movie.poster_path }}" class="w-full h-full "
                                     alt="{{ movie.title }}">
                            </div>
                            <div class="m-4  overflow-hidden flex-shrink-0 rounded-md cursor-pointer w-40">
                                <h5>{{ movie.title }} </h5>
                            </div>


                        </a>
                    {% endfor %}


                </div>
            </div>
        </section>
        <!--top_rated_movies-->
        <div class="text-gray-200 text-2xl p-8">Top rated</div>
        <section class='bg-primary_black px-5 flex-shrink-0 justify-center' style="overflow-x: scroll">
            <div class="px-5 w-10/12 relative">
                <div class="flex   items-center min-w-full">
                    {% for movie in top_rated_movies %}

                        <a href="{% url 'myApp1:movieDetail' movie_id=movie.id %}">

                            <div class=" h-40 m-4  bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer w-40">
                                <img src="{{ image_prefix }}{{ movie.poster_path }}" class="w-full h-full "
                                     alt="{{ movie.title }}">
                            </div>
                            <div class="m-4  overflow-hidden flex-shrink-0 rounded-md cursor-pointer w-40">
                                {{ movie.title }}
                            </div>


                        </a>
                    {% endfor %}


                </div>
            </div>
        </section>

    </main>

{% endblock content %}

templates/ordered_movies.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Ordered Movies
{% endblock title %}

{% block others %}
{% endblock others %}

{% block content %}


    {% include 'partials/navbar.html' %}
    <main class='bg-primary_black min-h-screen w-full'>
        <div class="py-32">
        </div>
        <!--ordered_movies-->
        <div class="text-gray-200 text-6xl p-8">Ordered movies</div>
        <section class='bg-primary_black px-5 flex-shrink-0 justify-center' style="overflow-x: scroll">
            <div class="px-5 w-10/12 relative">
                <div class="flex items-center min-w-full">
                    {% for movie in ordered_movies %}

                        <a href="{% url 'myApp1:movieDetail' movie_id=movie.id %}">

                            <div class=" h-40 m-4  bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer w-40">
                                <img src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" class="w-full h-full "
                                     alt="{{ movie.title }}">
                            </div>
                            <div class="m-4  overflow-hidden flex-shrink-0 rounded-md cursor-pointer w-40">
                                <h5>{{ movie.title }} </h5>
                            </div>
                        </a>


                    {% endfor %}


                </div>
            </div>
        </section>

    </main>

{% endblock content %}

templates/profileCreate.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Account Settings
{% endblock title %}

{% block content %}
    {% include 'partials/navbar.html' %}
    <section class='bg-primary_black min-h-screen py-20 md:py-32 flex-col flex items-center'
             style='background-image:url("{% static 'background_netflix.jpg' %}")'>
        <div class="flex flex-wrap justify-center  w-10/12  md:w-6/12">
            <form method='POST' class="w-full md:w-8/12 bg-gray-900 p-5 rounded-lg">
                {% if request.user.profiles.all|length > 5 %}
                    <p class='text-center text-xl'>

                        Sorry, you can't create any Profiles because you have exceeded the limit

                    </p>
                {% else %}

                    <h1 class="text-4xl text-center text-gray-100 font-medium">
                        Account Settings
                    </h1>
                    {% csrf_token %}

                    {{ form.errors }}
                    <div class="my-4">
                        <Label class='text-lg text-gray-200 font-medium mb-3'>
                            Profile Name
                        </Label>
                        <input required class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full"
                               type="text" name="name" id="id_name" placeholder="Profile name">
                    </div>
                    <div class="my-4">
                        <Label class='text-lg text-gray-200 font-medium mb-3'>
                            Email ID
                        </Label>
                        <input required class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full"
                               type="text" name="email" id="id_email" placeholder="Email ID">
                    </div>
                    <div class="flex justify-center items-center">
                        <button class="px-4 py-2 rounded-md outline-none bg-primary_red text-gray-100">Create Profile
                        </button>
                    </div>
                {% endif %}
            </form>
        </div>

    </section>

{% endblock content %}

templates/profileList.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Profile
{% endblock title %}

{% block content %}
    {% include 'partials/navbar.html' %}



    <section class='bg-primary_black min-h-screen py-20 md:py-0 flex-col flex justify-center items-center'>
        <h2 class="text-center font-medium text-5xl my-4 text-gray-100">
            Who's watching ?
        </h2>

        <div class="flex flex-wrap justify-center items-center w-10/12  md:w-6/12">

            {% for profile in profiles %}
                <a href="{% url 'core:watch' profile_id=profile.uuid %}">

                    <div class="w-32 h-32 m-4  bg-blue-500 flex justify-center items-center flex-col rounded-md cursor-pointer">
                        <p class='text-6xl'>
                            {{ profile.name | slice:":1" }}
                        </p>
                        <p class='text-lg'>
                            {{ profile.name }}
                        </p>
                    </div>
                </a>
            {% endfor %}

        </div>
        {% if request.user.profiles.all|length < 5 %}

            <div class="flex justify-center items-center">
                <a href="{% url 'myApp1:account_settings' %}">
                    {#                    'core:profile_create'#}
                    <button class="px-4 py-2 rounded-md outline-none bg-gray-400 text-gray-100">
                        Add A New Profile
                    </button>
                </a>
            </div>
        {% endif %}
    </section>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Sign up
{% endblock title %}

{% block other %}
{% endblock other %}

{% block content %}

    {% include 'partials/navbar.html' %}
    <header class="min-h-screen w-full bg-black bg-opacity-75 showcase relative border-gray-600 border-b-8 flex justify-center py-20 bg-no-repeat"
            style="background-image: url('{% static 'background_main.jpg' %}');">
        <div class="z-10 min-h-full py-32 md:py-0 text-gray-100 w-6/12  flex items-center flex-col">
            <form method='POST' class="bg-black bg-opacity-70  py-8 px-4 w-8/12 rounded-md" action="">
                <h1 class="text-4xl font-semibold text-center ">
                    Sign Up
                </h1>
                <div class="items-center text-center my-4 text-primary_red">
                    {% for m in messages %}
                        {{ m }}
                    {% endfor %}
                </div>
                {% csrf_token %}
                {% if form.errors %}

                    <div class="items-center text-center my-4 text-primary_red">
                        {{ form.errors.email }}
                        {{ form.errors.password1 }}
                        {{ form.errors.password2 }}

                    </div>
                {% endif %}

                <div class="my-3">
                    <Label class='text-lg font-medium mb-3'>
                        Username
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full"
                           type="text" aria-label="username" name="username" id="id_login" placeholder="Your Username">
                    {#                    <div class="text-black p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full">#}
                    {#                        {{ registerForm.username }}#}
                    {#                    </div>#}
                </div>

                <div class="my-3">
                    <Label class='text-lg font-medium mb-3'>
                        Email
                    </Label>
                    {#                    <div class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full">#}
                    {#                        {{ registerForm.email }}#}
                    {#                    </div>#}
                    {#                    <label for="id_email"></label>#}
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full"
                           type="email" aria-label="email"
                           name="email" id="id_email" placeholder="Your Email">

                    {#                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="email" name="email" id="id_email" placeholder="Your Email">#}
                </div>
                <div class='my-3'>
                    <Label class='text-lg font-medium mb-3'>
                        Password
                    </Label>
                    <input aria-label="Password"
                           class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full"
                           type="password" name="password1" id="id_password1" placeholder="Password">
                    {#                    <i class="text-black p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full">#}
                    {#                        {{ registerForm.password1 }}#}
                    {#                    </i>#}
                    {#                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="password" name="password1" id="id_password1" placeholder="Password">#}
                </div>
                <div class='my-3'>
                    <Label class='text-lg font-medium mb-3'>
                        Confirm Password
                    </Label>
                    {#                    <div class="text-black">#}
                    {#                        {{ registerForm.password2 }}#}
                    {#                    </div>#}
                    <input aria-label="Password"
                           class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="password"
                           name="password2" id="id_password2" placeholder="Password">
                </div>
                {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                {% endif %}
                <div class="flex justify-center items-center">
                    <button class="py-2 px-4 bg-primary_red text-gray-100 font-medium text-lg rounded-md" type="submit">
                        Sign Up
                    </button>
                </div>

                <div class="text-center mt-4">
                    <p>
                        Have account already ? <a href="{% url 'myApp1:loginPage' %}" class="text-blue-600"> Log In</a>
                    </p>
                </div>
            </form>
        </div>
    </header>
{% endblock content %}